model:
  model_root: "/workspace/pretrained_models/conformer_en_ctc_large"
  model_name: "stt_en_conformer_ctc_large.nemo"
  tokenizer_folder: "tokenizer"
  new_tokenizer_folder: "euro_meta_tokenizer"
  proto_file: "proto/file"
  proto_dir: "proto/dir"


training:
  data_dir: "/workspace/manifest_hf/euro/train_valid"
  train_manifest: "train.json"
  test_manifest: "valid.json"
  batch_size: 64  # Increase from 8 to 12
  max_steps: 10000000
  use_mixed_precision: true  # Add this flag for mixed precision

adapters:
  LinearAdapter:
    name: "LinearAdapter"
    dim: 32
    activation: "relu"
    norm_position: "pre"
  BottleneckAdapter:
    name: "BottleneckAdapter"
    dim: 64
    activation: "gelu"
    norm_position: "post"
  AttentionAdapter:
    name: "AttentionAdapter"
    dim: 48
    activation: "swish"
    norm_position: "pre"

experiment:
  exp_dir: "/workspace/experiments/euro"
  exp_name: "conformer-encoder-tune-euro-run1"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true
