model:
  model_root: "/external2/models/hf/stt_en_conformer_ctc_large/"
  model_name: "stt_en_conformer_ctc_large.nemo"
  tokenizer_folder: "tokenizer"
  new_tokenizer_folder: "new_tokenizer"
  proto_file: "proto/file"
  proto_dir: "proto/dir"

training:
  data_dir: "/external2/datasets/slurp/run_v1/processed"
  train_manifest: "train.json"
  test_manifest: "dev.json"
  batch_size: 16
  max_steps: 600000

adapters:
  LinearAdapter:
    name: "LinearAdapter"
    dim: 32
    activation: "relu"
    norm_position: "pre"
  BottleneckAdapter:
    name: "BottleneckAdapter"
    dim: 64
    activation: "gelu"
    norm_position: "post"
  AttentionAdapter:
    name: "AttentionAdapter"
    dim: 48
    activation: "swish"
    norm_position: "pre"

experiment:
  exp_dir: "/external2/karan_exp/experiments/"
  exp_name: "slurp-finetune-newtokenizer-euro-extended"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true
