model:
  model_root: "/external2/karan_exp/experiments/finetune-multidomain-alllang-100k-ctc/2024-07-18_00-21-12/checkpoints/"
  model_name: "finetune-multidomain-alllang-100k-ctc.nemo"
  tokenizer_folder: "tokenizer"
  new_tokenizer_folder: "new_tokenizer"
  proto_file: "proto/file"
  proto_dir: "proto/dir"

training:
  data_dir: "/home/ksingla/workspace/PromptingNemo/data_v2/synthetic/processed_r2/"
  train_manifest: "train.json"
  test_manifest: "valid.json"
  batch_size: 24
  max_steps: 60000

adapter:
  name: "AN4"
  dim: 32
  activation: "swish"
  norm_position: "pre"

experiment:
  exp_dir: "/external2/karan_exp/experiments/"
  exp_name: "adapater32-alllang-180k-ctc"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true

