model:
  model_root: "/external2/models/hf/stt_en_conformer_ctc_small/"
  model_name: "stt_en_conformer_ctc_small.nemo"
  tokenizer_folder: "tokenizer"
  new_tokenizer_folder: "new_tokenizer"
  proto_file: "proto/file"
  proto_dir: "proto/dir"

training:
  data_dir: "/external2/datasets/text/synthetic_non-command/processed/"
  train_manifest: "train_r5.json"
  test_manifest: "valid.json"
  batch_size: 16
  max_steps: 600000

adapters:
  LinearAdapter:
    name: "LinearAdapter"
    dim: 32
    activation: "relu"
    norm_position: "pre"
  BottleneckAdapter:
    name: "BottleneckAdapter"
    dim: 64
    activation: "gelu"
    norm_position: "post"
  AttentionAdapter:
    name: "AttentionAdapter"
    dim: 48
    activation: "swish"
    norm_position: "pre"

experiment:
  exp_dir: "/external2/karan_exp/experiments/"
  exp_name: "finetune-alllang-450k-ctc-small-r5"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true
