model:
  model_root: "/external2/models/hf/stt_en_conformer_ctc_large/"
  model_name: "stt_en_conformer_ctc_large.nemo"
  tokenizer_folder: "tokenizer"
  new_tokenizer_folder: "new_tokenizer"
  proto_file: "proto/file"
  proto_dir: "proto/dir"

training:
  data_dir: "/external2/datasets/text/synthetic/processed_r3/"
  train_manifest: "train.json"
  test_manifest: "valid.json"
  batch_size: 20
  max_steps: 60000

adapter:
  name: "AN4"
  dim: 32
  activation: "swish"
  norm_position: "pre"

experiment:
  exp_dir: "/external2/karan_exp/experiments/"
  exp_name: "finetune-alllang-130k-ctc-r3"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true

