apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-training-pvc
  namespace: dataprep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-training-pv
  resources:
    requests:
      storage: 6Ti
