adapter:
  activation: swish
  dim: 256
  enabled: true
  name: lang_adapter
  norm_position: pre
  unfreeze_decoder: true
experiment:
  always_save_nemo: true
  every_n_train_steps: 2000
  exp_dir: /mnt/nfs/experiments/
  exp_name: hi-vakyansh-meta-v15
  mode: min
  monitor: val_wer
  resume_if_exists: true
  save_top_k: 3
model:
  language_families:
  - INDO_ARYAN
  model_name: hi-vakyansh-meta-v13.nemo
  model_root: /mnt/nfs/experiments/hi-vakyansh-meta-v13/checkpoints/
  new_tokenizer_folder: hi_meta_tokenizer
  special_token_prefixes:
  - ENTITY_
  - INTENT_
  - EMOTION_
  - GENDER_
  - AGE_
  - KEYWORD_
  - LANG_
  tokenizer_folder: hi_meta_tokenizer
  tokenizer_langs:
    INDO_ARYAN:
      dir: /mnt/nfs/models/vakyansh_hi_conformer_large/hi_meta_tokenizer
      type: bpe
  use_aggregate_tokenizer: false
tag_classifier:
  categories:
  - AGE
  - GENDER
  - EMOTION
  enabled: true
  weight: 0.1
training:
  accumulate_grad_batches: 3
  batch_size: 24
  data_dir: /mnt/nfs/data/meta_stt_hi_set1
  devices: 1
  max_duration: 20.0
  max_steps: 200000
  min_duration: 0.1
  num_workers: 4
  optim:
    lr: 0.0003
    sched:
      max_steps: 200000
      min_lr: 1.0e-06
      warmup_steps: 1000
    weight_decay: 0.0
  pin_memory: true
  skip_audio_validation: true
  spec_augment:
    time_masks: 4
    time_width: 80
  test_manifest: valid.cleaned.json
  train_manifest: train_500k_selected.json
  use_family_loss_weights: false
  use_keyword_loss: false
  use_mixed_precision: true
