model:
  model_root: "/external1/pretrained_models/stt_en_fastconformer_ctc_large/"
  model_name: "stt_en_fastconformer_ctc_large.nemo"
  tokenizer_folder: "tokenizer"
  new_tokenizer_folder: "wellness_tokenizer_v4"
  proto_file: "proto/file"
  proto_dir: "proto/dir"

training:
  data_dir: "/external3/databases/wellness-jsonl/jsonl_files/data/"
  train_manifest: "train.jsonl"
  test_manifest: "valid.jsonl"
  batch_size: 4
  max_steps: 600000


adapters:
  LinearAdapter:
    name: "LinearAdapter"
    dim: 32
    activation: "relu"
    norm_position: "pre"
  BottleneckAdapter:
    name: "BottleneckAdapter"
    dim: 64
    activation: "gelu"
    norm_position: "post"
  AttentionAdapter:
    name: "AttentionAdapter"
    dim: 48
    activation: "swish"
    norm_position: "pre"

experiment:
  exp_dir: "/external3/databases/wellness-jsonl/experiment"
  exp_name: "wellness_adapter-bucket_data_himanshu_v4"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true
