apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-training-pv
spec:
  capacity:
    storage: 6Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.134.50.122
    path: /training
  mountOptions:
    - nfsvers=3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-training-pvc
  namespace: dataprep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: nfs-training-pv
  resources:
    requests:
      storage: 6Ti
