FLASK:
  SECRET_KEY: "a_secret_key"

TWILIO:
  ACCOUNT_SID: "AC036b65392d3ed4c975b62dfdd94dd6d8"
  AUTH_TOKEN: "67860a42a80d84e2cd2aa4e36443d616"
  AUTH_HEADER: "Basic QUMwMzZiNjUzOTJkM2VkNGM5NzViNjJkZmRkOTRkZDZkODo2Nzg2MGE0MmE4MGQ4NGUyY2QyYWE0ZTM2NDQzZDYxNg=="

OPENAI:
  API_KEY: "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"

SSL_CERT:
  FILE: "/usr/lib/ssl/certs/ca-certificates.crt"

SERVER:
  PORT: 5003

ASR:
  WEBSOCKET_URL: "wss://api.whissle.ai/socket.io/?EIO=4&transport=websocket"
