model:
  model_root: "/external1/experiments/hi-model-manifest-v3-tokenizer-extended/2025-03-31_18-39-41/checkpoints/"
  model_name: "hi-model-manifest-v3-tokenizer-extended.nemo"
  tokenizer_folder: "/external1/pretrained_models/speech-tagger_hi_ctc/model_manifest_tokenizer"
  new_tokenizer_folder: "/external1/pretrained_models/speech-tagger_hi_ctc/model_manifest_tokenizer"
  proto_file: "proto/file"
  proto_dir: "proto/dir"

training:
  data_dir: "/external4/datasets/AI4Bharat/hindi"
  train_manifest: "nemo_train.jsonl"
  test_manifest: "nemo_valid.jsonl"
  batch_size: 4  # Small batch size for testing
  max_steps: 100000  # Small max_steps for initial testing

experiment:
  exp_dir: "/external1/experiments/"
  exp_name: "hi-model-manifest-v3-tokenizer-extended-2"
  monitor: "val_wer"
  mode: "min"
  always_save_nemo: true
  save_best_model: true
